# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ qa ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DESCRIPTION_QA: "|QA|DEV|CUSTOM|"
  DESCRIPTION_PRD: "|PROD|DEV|CUSTOM|"
  APP_NAME: "api-comments"
  PATH_CHART: "./deploy/api-chart/"
  QA_VALUES: "./deploy/values-qa.yaml"
  QA_NAMESPACE: "qa"
  PRD_VALUES: "./deploy/values-prod.yaml"
  PRD_NAMESPACE: "prod"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./app/requirements.txt
      - name: Run tests
        env:
          MONGODB_URL: ${{ secrets.QA_MONGODB_URL }}
        run: cd ./app && python -m unittest tests/test_api.py 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.10.0      
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      # PRD
      - name: Build and push Docker images ${{ env.DESCRIPTION_PRD }}
        uses: docker/build-push-action@v2.6.1
        if: github.event.pull_request.base.ref == 'master'
        with: 
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            robsoncruz/api-comments:latest
      # QA
      - name: Build and push Docker images ${{ env.DESCRIPTION_QA }}
        uses: docker/build-push-action@v2.6.1
        if: github.ref != 'refs/heads/master' && github.event.pull_request.base.ref != 'master'
        with: 
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            robsoncruz/api-comments:${{ github.run_number }}

  CD:
   runs-on: ubuntu-latest
   needs: [CI]
   steps:
    - uses: actions/checkout@v2
    - name: Kubernetes set context
      uses: Azure/k8s-set-context@v1.1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_CONFIG }}
    # REPLACE - QA
    - name: Update env MONGO_URL ${{ env.DESCRIPTION_QA }}
      uses: jacobtomlinson/gha-find-replace@master
      if: github.ref != 'refs/heads/master' && github.event.pull_request.base.ref != 'master'
      with:
        find: "_MONGODB_URL_VALUE_"
        replace: "${{ secrets.QA_MONGODB_URL }}"
        include: "deploy/values-qa.yaml"
    - name: Update env TAG_VERSION ${{ env.DESCRIPTION_QA }}
      uses: jacobtomlinson/gha-find-replace@master
      if: github.ref != 'refs/heads/master' && github.event.pull_request.base.ref != 'master'
      with:
        find: "TAG_VERSION_VALUE"
        replace: "${{ github.run_number }}"
        include: "deploy/values-qa.yaml"
    # DEPLOY QA
    - name: Deploy ${{ env.DESCRIPTION_QA }}
      uses: WyriHaximus/github-action-helm3@v2
      with:
        exec: helm upgrade ${{ env.APP_NAME }} ${{ env.PATH_CHART }} --namespace=${{ env.QA_NAMESPACE }} --values=${{ env.QA_VALUES }}
    # REPLACE - PRD
    - name: Update env MONGO_URL ${{ env.DESCRIPTION_PRD }}
      uses: jacobtomlinson/gha-find-replace@master
      if: github.ref != 'refs/heads/master' && github.event.pull_request.base.ref != 'master'
      with:
        find: "_MONGODB_URL_VALUE_"
        replace: "${{ secrets.PRD_MONGODB_URL }}"
        include: "deploy/values-prod.yaml"
    - name: Update env TAG_VERSION ${{ env.DESCRIPTION_PRD }}
      uses: jacobtomlinson/gha-find-replace@master
      if: github.ref != 'refs/heads/master' && github.event.pull_request.base.ref != 'master'
      with:
        find: "TAG_VERSION_VALUE"
        replace: "${{ github.run_number }}"
        include: "deploy/values-prod.yaml"
    # DEPLOY PRD
    - name: Deploy ${{ env.DESCRIPTION_PRD }}
      uses: WyriHaximus/github-action-helm3@v2
      with:
        exec: helm upgrade ${{ env.APP_NAME }} ${{ env.PATH_CHART }} --namespace=${{ env.PRD_NAMESPACE }} --values=${{ env.PRD_VALUES }}
